"""empty message

Revision ID: 775525480ace
Revises: 81e9aa8c20ec
Create Date: 2025-07-03 14:53:36.935630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775525480ace'
down_revision = '81e9aa8c20ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=97), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_audit_logs',
    sa.Column('log_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('admin_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('admin_profiles',
    sa.Column('profile_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('admin_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('items',
    sa.Column('item_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('item_type', sa.Enum('lost', 'found', name='item_types'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('electronics', 'documents', 'clothing', 'accessories', 'other', name='item_categories'), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('item_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'recovered', 'claimed', name='item_statuses'), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('qr_code')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('idx_items_item_date', ['item_date'], unique=False)
        batch_op.create_index('idx_items_location', ['location'], unique=False)
        batch_op.create_index('idx_search', ['item_type', 'status', 'category'], unique=False)
        batch_op.create_index('idx_title', ['title'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('match', 'claim', 'system', name='notification_types'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('user_profiles',
    sa.Column('profile_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('user_profiles')
    op.drop_table('notifications')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('idx_title')
        batch_op.drop_index('idx_search')
        batch_op.drop_index('idx_items_location')
        batch_op.drop_index('idx_items_item_date')

    op.drop_table('items')
    op.drop_table('admin_profiles')
    op.drop_table('admin_audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
