"""empty message

Revision ID: db1f83114310
Revises: 
Create Date: 2025-07-14 12:11:26.943562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db1f83114310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_table('roles',
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('role_permission',
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('log_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('items',
    sa.Column('item_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=10), nullable=False),
    sa.Column('location_found', sa.String(length=100), nullable=False),
    sa.Column('date_found', sa.Date(), nullable=False),
    sa.Column('image_filename', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('image_features', sa.JSON(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('item_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('claim_details', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('finder_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('proof_filename', sa.String(length=128), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finder_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('item_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('claim_messages',
    sa.Column('message_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('claim_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('sender_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('claim_reviews',
    sa.Column('review_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('claim_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('reviewer_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('rating', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.claim_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_reviews')
    op.drop_table('claim_messages')
    op.drop_table('notifications')
    op.drop_table('claims')
    op.drop_table('items')
    op.drop_table('admin_audit_logs')
    op.drop_table('users')
    op.drop_table('role_permission')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
